replicaCount: 1

image:
  repository: bn089/web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  API_HOST: "http://api:3001"
  PORT: "3000"

resources:
  limits:
    cpu: "1"
    memory: "128Mi"
  requests:
    cpu: "1"
    memory: "64Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5
