apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
data:
  PORT: "{{ .Values.env.PORT }}"
  DB_HOST: "{{ .Values.env.DB_HOST }}"
  DB_PORT: "{{ .Values.env.DB_PORT }}"
  DB_USER: "{{ .Values.env.DB_USER }}"
  DB_NAME: "{{ .Values.env.DB_NAME }}"
